### ISSUE TITLE
Bad file descriptor on Windows while running the example

### ISSUE THREAD

**Issue by kke** [acook/remedy#13]
First I get some garbage:

```
[?25l
```

When I press a key, I get `Bad file descriptor`

![image](https://cloud.githubusercontent.com/assets/224971/20687189/2f777b8a-b5c4-11e6-822f-7765cf2cc774.png)

**Comment by acook** [comment]
1 - Garbage Written to Screen
------------------------------

The garbage is Remedy trying to talk to a VT100 TTY using ANSI escape sequences.

ANSI support can be obtained in a Windows console using [ANSICON](https://github.com/adoxa/ansicon). 

Remedy should work out-of-the-box using Windows Subsystem for Linux or Cygwin, but the reason for the above failure in a native console is that Ruby doesn't abstract the Windows console API effectively - and the Windows NT console API is fundamentally and radically different from the VT100 style. 

2 - File Descriptor Issue
------------------------

The failing line of code in Remedy is actually line 28 of console.rb:

~~~ruby
input.echo = false
~~~

But the `ensure` block is masking the error because another exception is `raise`d in the ensure block on line 33:

~~~ruby
input.echo = true
~~~

Both lines are calling `IO#echo` which is supplied by Ruby stdlib `io/console`:

~~~c
console_set_echo(VALUE io, VALUE f)
{
    conmode t;
    rb_io_t *fptr;
    int fd;

    GetOpenFile(io, fptr);
    fd = GetReadFD(fptr);
    if (!getattr(fd, &t)) rb_sys_fail(0);
    if (RTEST(f))
        set_echo(&t, NULL);
    else
        set_noecho(&t, NULL);
    if (!setattr(fd, &t)) rb_sys_fail(0);
    return io;
}
~~~

Ruby's `GetReadFD` fails for stdin when called within a Windows console, which may be a bug, but I doubt they intend to fix it.

However, a possible solution to this second issue might be to use the [`io-console` gem](https://github.com/nobu/io-console), just make sure it is loaded before you do `require 'remedy'` and according to `io-console`'s documentation it should just work. Give it a shot and let me know if it works for you.

**Comment by kke** [comment]
Pfft. `The 'io-console' native gem requires installed build tools.`

I think I'm just going to suggest people use WSFL or Cygwin. Maybe I'll give it a go myself so I can tell how it goes.

Thanks for the excellent reply anyway!

**Comment by kke** [comment]
Yes, everything works just fine in WFL. Good enough.

**Comment by acook** [comment]
I'm going through and closing old issues, please let me know if you run into anything else or found another workaround!
